name: APFPV Build

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  TAG_NAME: ${{ github.event.release.tag_name }}

jobs:
  buildroot:
    name: Firmware
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:

          # APFPV
          - ssc30kq_apfpv
          - ssc338q_apfpv
          - ssc378qe_apfpv

            # # FPV
            # - hi3516ev200_fpv
            # - hi3516ev300_fpv
            # - hi3536dv100_fpv
            # - gk7205v200_fpv
            # - gk7205v210_fpv
            # - gk7205v300_fpv
            # - ssc30kq_fpv
            # - ssc338q_fpv
            # - ssc378qe_fpv
            # - ssc338q_fpv_caddx-fly
            # - ssc338q_fpv_emax-wyvern-link
            # - ssc338q_fpv_openipc-mario-aio
            # - ssc338q_fpv_openipc-thinker-aio
            # - ssc338q_fpv_openipc-urllc-aio
            # - ssc338q_fpv_runcam-wifilink

            # # Ruby
            # - ssc30kq_rubyfpv_generic
            # - ssc338q_rubyfpv_generic
            # - ssc338q_rubyfpv_thinker_internal_wifi

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Prepare firmware
        run: |
          echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
          echo CACHE_DATE=$(date +%m) >> ${GITHUB_ENV}
          INPUT=${{inputs.platform}}
          MATRIX=$(echo ${{matrix.platform}} | cut -d_ -f1)
          if [ -z ${INPUT} ] || [ ${INPUT} = ${MATRIX} ]; then
            echo RUN=${MATRIX} >> ${GITHUB_ENV}
          fi

      - name: Setup ccache
        if: env.RUN
        uses: actions/cache@v4
        with:
          path: /tmp/ccache
          key: ${{matrix.platform}}-${{env.CACHE_DATE}}

      - name: Build firmware
        if: env.RUN
        run: |
          export GIT_HASH=$(git rev-parse --short ${GITHUB_SHA})
          export GIT_BRANCH=${GITHUB_REF_NAME}
          echo GIT_HASH=${GIT_HASH} >> ${GITHUB_ENV}
          echo GIT_BRANCH=${GIT_BRANCH} >> ${GITHUB_ENV}

          mkdir -p /tmp/ccache
          ln -s /tmp/ccache ${HOME}/.ccache

          NAME=${{matrix.platform}}
          bash builder.sh ${NAME}
          cd openipc

          TIME=$(date -d @${SECONDS} +%M:%S)
          echo TIME=${TIME} >> ${GITHUB_ENV}
          COMMON=$(echo ${NAME} | awk -F_ '{print NF-1}')

          NORFW=$(find output/images -name openipc*nor*)
          if [ ! -z ${NORFW} ]; then
            if [ ${COMMON} -eq 1 ]; then
              echo NORFW=openipc/${NORFW} >> ${GITHUB_ENV}
            else
              mv ${NORFW} ../${NAME}-nor.tgz
              echo NORFW=${NAME}-nor.tgz >> ${GITHUB_ENV}
            fi
          fi

          NANDFW=$(find output/images -name openipc*nand*)
          if [ ! -z ${NANDFW} ]; then
            if [ ${COMMON} -eq 1 ]; then
              echo NANDFW=openipc/${NANDFW} >> ${GITHUB_ENV}
            else
              mv ${NANDFW} ../${NAME}-nand.tgz
              echo NANDFW=${NAME}-nand.tgz >> ${GITHUB_ENV}
            fi
          fi

          if [ -z ${NORFW} ] && [ -z ${NANDFW} ]; then
            exit 1
          fi

      - name: Upload test firmware to artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{matrix.platform}}
          path: output/images/openipc*nor*

      - name: Upload release firmware
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{env.TAG_NAME}}
          token: ${{ secrets.RELEASE_TOKEN }}
          files: |
            ${{env.NORFW}}
            output/images/openipc*.bin
